#!/usr/bin/env node
/* =============================================================
   The loading bar's size table: every file the game fetches, with its
   size on disk, written to js/asset-manifest.js.

   js/preload.js weighs each file by these sizes, so the bar moves by
   bytes rather than by files — a 7KB voice clip and a 1.2MB piece of
   music are not the same step — and refines each one with the
   Content-Length the server sends.

   Run by .githooks/pre-commit on every commit that touches the game, so
   the table always matches the files; `node tools/manifest.js` by hand
   does the same. Prints the file it wrote if it changed it.
   ============================================================= */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const size = function (rel) { return fs.statSync(path.join(ROOT, rel)).size; };
const list = function (dir, re) {
  return fs.readdirSync(path.join(ROOT, dir)).filter(function (f) { return re.test(f); })
    .sort().map(function (f) { return dir + '/' + f; });
};

const files = {};
// the pictures, and the fonts the page draws in (the -latin-ext files
// are only ever asked for by a character outside the Latin set, so the
// loader does not fetch them and they are not listed)
list('assets', /\.webp$/).forEach(function (f) { files[f] = size(f); });
list('assets/fonts', /-(latin|math)\.woff2$/).forEach(function (f) { files[f] = size(f); });
// every sound: the music and each voice clip, Ogg Opus
list('sfx', /\.ogg$/).forEach(function (f) { files[f] = size(f); });
list('sfx/voices', /\.ogg$/).forEach(function (f) { files[f] = size(f); });

const out = '/* Generated by tools/manifest.js — every file the game fetches, with\n' +
  '   its size on disk, for the loading bar (js/preload.js). Do not edit:\n' +
  '   the commit hook writes it. */\n' +
  'window.ASSET_MANIFEST = ' + JSON.stringify(files, null, 1) + ';\n';
const file = path.join(ROOT, 'js/asset-manifest.js');
const was = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
if (out !== was) { fs.writeFileSync(file, out); console.log('js/asset-manifest.js'); }
